name: CI

on: 
  push:
    paths-ignore:
      - 'doc/**'
      - '*.md'
  
jobs:
  CI:
    name: Test
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    if: true
    steps:
  
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - uses: game-ci/unity-test-runner@v2
        id: tests
          
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Results
          path: ${{ steps.tests.outputs.artifactsPath }}
          retention-days: 1

      - name: Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/git
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
